### ISSUE TITLE
ch-3-ex-1 and ch-3-ex-2 throws: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by mathiasconradt** [oauthinaction/oauth-in-action-code#18]
When running the exercises with the complete client code (client.js), fetching the token works, but when trying to request the protected resources, an error is thrown on the protectedResources server:

```
$ node protectedResource.js 
OAuth Resource Server is listening at http://127.0.0.1:9002
Incoming token: 4ZYxN6lwg71yGIDb5UoOIlqdcNEqL8To
fs.js:144
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:144:11)
    at Object.close (fs.js:399:20)
    at next (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/nosql/index.js:2388:8)
    at /home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/nosql/index.js:2413:4
    at FSReqCallback.wrapper [as oncomplete] (fs.js:478:5)
```

causing the client to throw:

```
Error: socket hang up
    at doRequest (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/sync-request/index.js:31:11)
    at /home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/client.js:127:17
    at Layer.handle [as handle_request] (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/layer.js:95:5)
    at /home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/index.js:335:12)
    at next (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/index.js:317:13)
    at /home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/index.js:335:12)
    at next (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/router/index.js:275:10)
    at query (/home/myuser/Projects/oauth-in-action-code/exercises/ch-3-ex-2/node_modules/express/lib/middleware/query.js:45:5)
```

Using: 

node 11.1.0
npm 6.4.1

**Comment by mathiasconradt** [comment]
I downgraded to node 8.0 and it works fine. So the packages are not compatible to node 11.1.0. The book unfortunately does not mention which node version it's compatible with, but I figured 8.0 would work since the book was published in 2017.

**Comment by inherithandle** [comment]
I had the same problem. you're a lifesaver. thanks 👍

**Comment by welkie** [comment]
Thanks for posting this. I ran into this too today. I'm actually surprised the authors chose to use a synchronous HTTP library for this chapter. My first thought was they might want to keep the code as simple looking as possible, and many people have issues understanding callback style asynchronous JS code. But then I noticed they're using a library for a simple NoSQL database (called "nosql") which uses callbacks for its interface anyways.

I know that promises were still a bit up in the air back when this book was people made, but I'm surprised they didn't just use a popular library like request or axios, or even just use XHR. I think it would have avoided this issue.

**Comment by jricher** [comment]
We weren't targeting professional JS developers with our examples, and instead we wanted our code to be as not-javascripty as we could manage it to be, so that people could focus on the underlying protocols they're implementing and not on the language the examples were in. As a consequence, we tried to avoid async callbacks as much as possible, but there were a few places like `nosql` and some of the jose stuff where we had to use it. 

We made the code based on what was available when we wrote the book -- which was largely well before the book was even written. The code examples need to be scrubbed and updated, but unfortunately neither of the authors have had the bandwidth to do that at this time.

**Comment by jricher** [comment]
Also, the database is used so that the AS and RS components can be completely separate from each other. The AS creates the token, the RS reads the token, and they're not always on the same machine -- and in today's OAuth world, they're usually not.

**Comment by welkie** [comment]
@jricher Would you be open to me doing a post-publish technical proof? I'm currently proofing another Manning book and I'm actually enjoying the process. I'm planning on going through OAuth2 in Action cover to cover before the end of the month. I could report back about what code doesn't work and put forth suggestions. I don't know if Manning would allow you to reopen the MEAP for this book though, it might be more trouble than it's worth.

**Comment by Antoine-Poincare** [comment]
in ch-3-ex-1/node_modules/nosql/index.js:2388:8 ```fs.close(fd);```  should be
```
fs.close(fd, function(err, result) {});
```
and problem solved

**Comment by bill-barron** [comment]
Here's the relevant issue on the nosql repository:
https://github.com/petersirka/nosql/issues/46

**Comment by myhelloos** [comment]
i upgrade the nosql to 6.1.0 version

and change the code of `protectedResource` from 

```
nosql.one(function(token) {
        if (token.access_token == inToken) {
                return token;
        }
}, function(err, token) {
        if (token) {
                console.log("We found a matching token: %s", inToken);
        } else {
                console.log('No matching token was found.');
        }
        req.access_token = token;
        next();
        return;
        });
});
```

to 


```
nosql.find().make(function(filter) {
    filter.where('access_token', '=', inToken);

    filter.callback(function(err, token) {
			if (token) {
				console.log("We found a matching token: %s", inToken);
			} else {
				console.log('No matching token was found.');
			}
			req.access_token = token;
			next();
			return;
    });
	});
```
