### ISSUE TITLE
ch-3-ex-1 protected resource not working (ERR_INVALID_CALLBACK)

### ISSUE THREAD

**Issue by welkie** [oauthinaction/oauth-in-action-code#20]
I tried working through Chapter 3 Exercise 1. I copy and pasted the code for the client from the appendix. I notice the code for the authorization server and protected resource appears to be completely filled in already, so I didn't make any changes to that code. However, at the end of the exercise when I get a token and then click Get Protected Resource, I get the following error message in the terminal for my protected resource server:

```
node .\protectedResource.js
OAuth Resource Server is listening at http://127.0.0.1:9002
Incoming token: xmFD2F9vg6AF4tQGLIzX19Vm27gI426K
fs.js:142
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:142:11)
    at Object.close (fs.js:400:20)
    at next (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\nosql\index.js:2388:8)
    at C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\nosql\index.js:2413:4
    at FSReqCallback.wrapper [as oncomplete] (fs.js:479:5)
```

Throughout this process, the following appears in the terminal for the client server. It appears to have no problem getting the authorization code and then the access token. The logs say it begins to make the request for the protected resource with an access code:

```
node .\client.js
OAuth Client is listening at http://127.0.0.1:9000
redirect http://localhost:9001/authorize?response_type=code&client_id=oauth-client-1&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fcallback&state=uaupQrqmFN8xKZzps0WT8YgSxdGeNJQR
Requesting access token for code 7ZsNkiot
Got access token: 11zLkASTHepVKxWQ7lClBAEX8iWYcFRs
(node:8588) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Making request with access token 11zLkASTHepVKxWQ7lClBAEX8iWYcFRs
Error: read ECONNRESET
    at doRequest (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\sync-request\index.js:31:11)
    at C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\client.js:120:17
    at Layer.handle [as handle_request] (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\index.js:275:10)
    at expressInit (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\router\index.js:275:10)
    at query (C:\Users\mattw\repos\oauth-in-action-code\exercises\ch-3-ex-1\node_modules\express\lib\middleware\query.js:45:5)
```

A portion of this error appears in my web browser too - the part that begins with `Error: read ECONNRESET`.

**Comment by welkie** [comment]
Got this to work by copy and pasting code again from the book. May have been a bad copy and paste at first.

**Comment by welkie** [comment]
Actually still got this issue intermittently. But realized via https://github.com/oauthinaction/oauth-in-action-code/issues/18 that it's an issue with running modern Node.
